name: deploy for dev

on:
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'docker-compose.yml'
      - 'bin/*'

jobs:
  deploy-dev:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2


