name: Build app and deploy to aliyun
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # 安装Node13
      - name: use Node.js 13.2.0
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      # 安装依赖
      - name: npm install
        run: npm install
      # 打包
      - name: npm build
        run: npm run build
      - name: ssh key
        run: |
          mkdir -p ~/.ssh/
          # echo "${{secrets.MAC_LOCAL}}" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts
      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.MAC_LOCAL }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录，编译后生成的文件目录
          SOURCE: "./dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "39.100.253.134"
          # 用户
          REMOTE_USER: "carr"
          # 目标地址 你在服务器上部署代码的地方
          TARGET: "/home/carr"
