name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on:  ubuntu-lastest
  steps:
    # 获取源码
    - name: checkout
      uses: actions/checkout@v2
    # 安装node
    - name: use Node.js
    - uses: actions/setup-node@v1
      with:
          node-version: 13.2.0
    # 安装依赖
    - name: install
    - uses: npm install
    # 打包
    - name: build
      run: npm run build:prod
    # 部署
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        # 私钥
        SSH_PRIVATE_KEY: ${{ secrets.ECS_CARR }}
        # scp参数
        ARGS: "-avzr --delete"
        # 源目录，编译后生成的文件目录
        SOURCE: "./dist"
        # 服务器ip：换成你的服务器IP
        REMOTE_HOST: "39.100.253.134"
        # 用户
        REMOTE_USER: "carr"
        # 目标地址 你在服务器上部署代码的地方
        TARGET: "/home/carr"
