name: deploy for dev

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'docker-compose.yml'

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key
#         run: |
#             mkdir -p ~/.ssh/
#             echo "${{secrets.ECS_ROOT}}" > ~/.ssh/id_rsa
#             chmod 600 ~/.ssh/id_rsa
#             ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts
#       - name: deploy
#         run: |
#           ssh root@39.100.253.134
#           cd /home
#           git remote add origin https://github.com:${{secrets.ECS_ROOT}}@github.com/lzjdp/automation
#           git pull origin master
#           git remote remove origin




