name: deploy for dev

on:
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'docker-compose.yml'
      - 'bin/*'

jobs:
  deploy-dev:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key
        run: |
            mkdir -p ~/.ssh/
            echo ""
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts


