name: deploy for dev

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows'
      - 'src/**'
      - 'docker-compose.yml'
      - 'bin/*'

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key
        run: |
            mkdir -p ~/.ssh/
            echo "${{secrets.MAC_LOCAL}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts
      - name: deploy
        run: |
          ssh carr@39.100.253.134
          cd /home/carr
          git remote add origin https://github.com:${{secrets.MAC_LOCAL}}@github.com/lzjdp/automation
          git pull origin master
          git remote remove origin




